#!/usr/bin/env python3
"""Build the SRT-Translator executable.

The version is derived automatically from git tags (``setuptools_scm`` when it
is installed, otherwise ``git describe``), then baked into ``_version.py`` so
the frozen executable can report it. Run ``python build.py`` to regenerate the
version and build ``dist/SRT-Translator.exe``.

Release workflow:
    git tag v1.2.0
    git push origin v1.2.0
    python build.py
"""
import datetime
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))


def git(*args):
    return subprocess.check_output(
        ["git", *args], cwd=ROOT, text=True, stderr=subprocess.DEVNULL
    ).strip()


def compute_version():
    """Return a PEP 440-ish version derived from the nearest git tag."""
    # Prefer setuptools_scm when available.
    try:
        from setuptools_scm import get_version

        return get_version(root=ROOT)
    except Exception:
        pass

    try:
        desc = git("describe", "--tags", "--match", "v*", "--long", "--dirty")
    except Exception:
        return "0.0.0"

    match = re.match(r"v(\d+)\.(\d+)\.(\d+)-(\d+)-g([0-9a-f]+)(-dirty)?$", desc)
    if not match:
        return "0.0.0"

    major, minor, patch, commits, _sha, dirty = match.groups()
    if int(commits) == 0:
        version = f"{major}.{minor}.{patch}"
    else:
        # Commits after the last release -> next patch, marked as a dev build.
        version = f"{major}.{minor}.{int(patch) + 1}.dev{commits}"
    if dirty:
        version += ".dirty"
    return version


def write_version_module(version):
    try:
        git_hash = git("rev-parse", "--short", "HEAD")
    except Exception:
        git_hash = ""
    build_date = datetime.date.today().isoformat()

    content = (
        "# Auto-generated by build.py - do not edit, do not commit.\n"
        f'VERSION = "{version}"\n'
        f'GIT_HASH = "{git_hash}"\n'
        f'BUILD_DATE = "{build_date}"\n'
    )
    with open(os.path.join(ROOT, "_version.py"), "w", encoding="utf-8") as f:
        f.write(content)
    return git_hash, build_date


def main():
    version = compute_version()
    git_hash, build_date = write_version_module(version)
    print(f"Version: {version} (g{git_hash}, {build_date})")

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "SRT-Translator.spec", "--noconfirm", *sys.argv[1:],
    ]
    return subprocess.call(cmd, cwd=ROOT)


if __name__ == "__main__":
    sys.exit(main())
